### ISSUE TITLE
Requirements issues

### ISSUE THREAD

**Issue by Qinusty** [se7entyse7en/pydockenv#54]
Looking to give this a go, I installed via pypi as directed in the README.

Firstly, on attempted creation I got a massive stack trace which came down to a missing requirement of docker-py. So I installed this with `pip install --user docker-py`.

Attempting to create a pydockenv again, I get 
```python
Creating environment dockenv with python version latest...
Traceback (most recent call last):
  File "<HOME>/.local/lib/python3.7/site-packages/pydockenv/commands/pydockenv.py", line 34, in create
    image = client.images.get(image_name)
AttributeError: 'function' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<HOME>/.local/lib/python3.7/site-packages/pydockenv/commands/pydockenv.py", line 362, in <module>
    cli()
  File "<HOME>/.local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "<HOME>/.local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "<HOME>/.local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<HOME>/.local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<HOME>/.local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "<HOME>/.local/lib/python3.7/site-packages/pydockenv/commands/pydockenv.py", line 35, in create
    except docker.errors.ImageNotFound:
AttributeError: module 'docker.errors' has no attribute 'ImageNotFound'
```

Solved this with `pip install --user docker`

Then 

```python
 Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<HOME>/.local/lib/python3.7/site-packages/pydockenv/commands/pydockenv.py", line 13, in <module>
    client = docker.from_env()
  File "<HOME>/.local/lib/python3.7/site-packages/docker/client.py", line 85, in from_env
    timeout=timeout, version=version, **kwargs_from_env(**kwargs)
  File "<HOME>/.local/lib/python3.7/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "<HOME>/.local/lib/python3.7/site-packages/docker/api/client.py", line 128, in __init__
    config_dict=self._general_configs, credstore_env=credstore_env,
TypeError: load_config() got an unexpected keyword argument 'config_dict'
python: can't open file 'create': [Errno 2] No such file or directory
```

Which version of docker/docker-py is compatible with the project?

For reference, `pip freeze | grep dock` gives:

```
docker==3.7.2
docker-py==1.10.6
docker-pycreds==0.4.0
pydockenv==0.2.1
```

**Comment by se7entyse7en** [comment]
I don't know why the instructions in the README didn't work for you actually, most probably it has some conflicting dep with something that is already installed in your user installation directory.

BTW I think that your problem is `docker-py`, I don't have it locally and by looking at pypi it seems that it is an older version of the `docker` library. It seems that at some point it changed name. Take a look [here](https://pypi.org/project/docker-py/#history) and [here](https://pypi.org/project/docker/#history).
